version: "2"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:14.4.0
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

  meillisearch:
    image: getmeili/meilisearch:v0.28.1
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=changeme

volumes:
  postgresql_data:
    driver: local
